gitrepos:
  build: git-repos
  volumes:
    - './build/git-repos:/git'

postgresql:
  build: postgresql
  volumes:
    - './build/postgresql/ubuntu/20.04:/mnt'

redis:
  build: redis
  volumes:
    - './build/redis/ubuntu/20.04:/redis'

ruby:
  build: ruby
  volumes:
    - './build/ruby/ubuntu/20.04:/ruby'

nginx:
  build: nginx
  volumes:
    - './build/nginx/ubuntu/20.04:/nginx'

memcached:
  build: memcached
  volumes:
    - './build/memcached/ubuntu/20.04:/memcached'

monit:
  build: monit
  volumes:
    - './build/monit/ubuntu/20.04:/monit'

docker:
  build: docker
  volumes:
    - './build/docker/ubuntu/20.04:/docker'

mongodb:
  build: mongodb
  volumes:
    - './build/mongodb/ubuntu/20.04:/mongodb'

compose:
  build: compose
  volumes:
    - './build/compose:/compose'
