mypsql:
  build: postgresql
  volumes:
    - '/srv/downloads/postgresql/ubuntu/14.04:/mnt'

myruby:
  build: ruby
  volumes:
    - '/srv/downloads/ruby/ubuntu/14.04:/ruby'

mynginx:
  build: nginx
  volumes:
    - '/srv/downloads/nginx/ubuntu/14.04:/nginx'
